# Generated by Django 5.1.7 on 2025-05-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("preview", models.ImageField(blank=True, null=True, upload_to="course_previews/")),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("preview", models.ImageField(blank=True, null=True, upload_to="lesson_previews/")),
                ("video_link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_method", models.CharField(max_length=10)),
                ("stripe_product_id", models.CharField(blank=True, max_length=100, null=True)),
                ("stripe_price_id", models.CharField(blank=True, max_length=100, null=True)),
                ("stripe_session_id", models.CharField(blank=True, max_length=100, null=True)),
                ("payment_url", models.URLField(blank=True, max_length=500, null=True)),
                ("is_paid", models.BooleanField(default=False)),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
